name: "BSF Code Reviewer"
description: "PR ewviewer is a lightweight tool for reviewing GitHub Pull Requests, offering a clean interface to view diffs, leave comments, and manage multiple PRs with ease."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  JIRA_BASE_URL:
    description: "JIRA base URL."
    required: true
  JIRA_USERNAME:
    description: "JIRA username."
    required: true
  JIRA_TOKEN:
    description: "JIRA token."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  INCLUDE_EXTENSIONS:
    description: 'File extensions to include in the review (comma-separated, e.g., ".py,.js,.html")'
    required: false
    default: "php, js, jsx, ts, tsx, css, scss, html"
  EXCLUDE_EXTENSIONS:
    description: 'File extensions to exclude from the review (comma-separated)'
    required: false
    default: "md, yml, lock, json, xml, txt, csv, log, sql, env, gitignore, gitattributes, gitmodules, gitkeep, git, gitconfig"
  EXCLUDE_PATHS:
    description: 'Paths to exclude from review (comma-separated, e.g., "test/,docs/")'
    required: false
    default: "node_modules/,vendor/,assets/css/minified/,assets/js/minified/,assets/build/, dist/, build/, public/, .next/, .nuxt/, .cache/, .git/, .github/, .idea/, .vscode/, .gitignore, .gitattributes, .gitmodules, .gitkeep, .gitconfig"
  ACTION_CONTEXT:
    description: 'Review context (e.g., "CHECK_SHORTCODE")'
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/bundle.js"
branding:
  icon: "aperture"
  color: "green"